package inputdata.Entities;
// Generated Jan 25, 2016 12:01:24 PM by Hibernate Tools 4.3.1



/**
 * Identitas generated by hbm2java
 */
public class Identitas  implements java.io.Serializable {


     private int id;
     private String firstName;
     private String lastName;

    public Identitas() {
    }

	
    public Identitas(int id) {
        this.id = id;
    }
    public Identitas(int id, String firstName, String lastName) {
       this.id = id;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


